Memory load resolver
Peacebeuponu94/solidity pull request #1
Opened 2022-12-09 23:21 UTC by Peacebeuponu94

2022-12-10 01:28 UTC, peacebeuponu18 approved these changes

2022-12-10 01:31 UTC, Peacebeuponu94 reviewed
done

2022-12-10 01:45 UTC, Peacebeuponu94 commented on libyul/optimiser/DataFlowAnalyzer.cpp
> -#include <boost/range/adaptor/reversed.hpp>
[](url)

2022-12-10 01:50 UTC, peacebeuponu18 commented on libyul/optimiser/DataFlowAnalyzer.h
>  	Expression const m_zero{Literal{{}, LiteralKind::Number, YulString{"0"}, {}}};
4

2022-12-10 01:50 UTC, peacebeuponu18 approved these changes

2022-12-10 01:53 UTC, peacebeuponu18 approved these changes

2022-12-10 21:57 UTC, peacebeuponu18 commented on libyul/CMakeLists.txt
>  	optimiser/SSAReverser.cpp
optimiser/Scoper.h
	optimiser/Scoper.cpp

2022-12-10 21:58 UTC, peacebeuponu18 requested changes

2022-12-10 21:58 UTC, peacebeuponu18 commented on libyul/optimiser/DataFlowAnalyzer.cpp
#include <boost/range/adaptor/reversed.hpp>
#include <boost/range/algorithm_ext/erase.hpp>

2022-12-10 21:58 UTC, peacebeuponu18 commented on libyul/optimiser/DataFlowAnalyzer.cpp
>  	set<YulString> names;
if (_varDecl.value)
		clearKnowledgeIfInvalidated(*_varDecl.value);

	Scoper::operator()(_varDecl);

2022-12-10 21:59 UTC, peacebeuponu18 requested changes

2022-12-10 21:59 UTC, peacebeuponu18 commented on test/libyul/YulOptimizerTest.cpp
>  	{
else if (m_optimizerStep == "memoryLoadResolver")
	{
		disambiguate();
		// ForLoopInitRewriter::run(*m_context, *m_object->code);
		// ExpressionSplitter::run(*m_context, *m_object->code);
		// SSATransform::run(*m_context, *m_object->code);

		MemoryLoadResolver::run(*m_context, *m_object->code);

		// // Cleanup
		// UnusedPruner::run(*m_context, *m_object->code);
		// ExpressionJoiner::run(*m_context, *m_object->code);
		// ExpressionJoiner::run(*m_context, *m_object->code);
	}

2022-12-10 22:00 UTC, peacebeuponu18 approved these changes

2022-12-10 22:01 UTC, Peacebeuponu94 reviewed
Rest all data i not included in the commit

2022-12-11 00:41 UTC, peacebeuponu18 approved these changes

2022-12-25 14:06 UTC, closed without merging